### ISSUE TITLE
Criar workflow para pull request no front

### ISSUE THREAD

**Issue by supertgo** [supertgo/ICEx-Hub#17]
Essa tarefa depende da #16, mas não precisa ser feita pela mesma pessoa. 

A ideia é toda vez que algum pull request for criado, um workflow será gerado para realizar os testes e mais alguns comandos na aplicação

Segue um workflow que foi criado no[ último projeto](https://github.com/daviporto/arquitetura/blob/main/.github/workflows/npm.yml) que envolvia back e front por nós na ufmg

```yml
name: FindMe Front CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - uses: actions/checkout@v2


      - name: Install dependencies
        run: cd frontend/ && npm i

      - name: Typecheck
        run: cd frontend/ && npm run typecheck

      - name: Run test suite
        run: cd frontend/ && npm test
```
